-- ========================================
-- 7. CONSULTAS SQL COMPLEXAS (RELATÓRIOS) 
-- ========================================

-- Tabela: usuarios
CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(100) NOT NULL,
    tipo_usuario VARCHAR2(20) NOT NULL 
        CONSTRAINT chk_tipo_usuario CHECK (tipo_usuario IN ('cidadao', 'voluntario', 'orgao_publico')),
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela: tipos_ocorrencia
CREATE TABLE tipos_ocorrencia (
    id_tipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL
);

-- Tabela: ocorrencias
CREATE TABLE ocorrencias (
    id_ocorrencia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuarios(id_usuario),
    id_tipo NUMBER REFERENCES tipos_ocorrencia(id_tipo),
    descricao VARCHAR2(1000),
    latitude NUMBER(10,7),
    longitude NUMBER(10,7),
    data_ocorrencia TIMESTAMP NOT NULL,
    nivel_risco VARCHAR2(20) NOT NULL 
        CONSTRAINT chk_nivel_risco CHECK (nivel_risco IN ('baixo', 'moderado', 'alto')),
    status VARCHAR2(20) NOT NULL
);

-- Tabela: alertas
CREATE TABLE alertas (
    id_alerta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    mensagem VARCHAR2(1000) NOT NULL,
    nivel_urgencia VARCHAR2(20) NOT NULL 
        CONSTRAINT chk_nivel_urgencia CHECK (nivel_urgencia IN ('baixa', 'media', 'alta')),
    data_emissao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_ocorrencia NUMBER REFERENCES ocorrencias(id_ocorrencia),
    fonte VARCHAR2(50)
);

-- Tabela: abrigos
CREATE TABLE abrigos (
    id_abrigo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    endereco VARCHAR2(150),
    capacidade_total NUMBER NOT NULL,
    vagas_disponiveis NUMBER NOT NULL,
    telefone VARCHAR2(20),
    status VARCHAR2(20) NOT NULL
);

-- Tabela: checkins_abrigos
CREATE TABLE checkins_abrigos (
    id_checkin NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER REFERENCES usuarios(id_usuario),
    id_abrigo NUMBER REFERENCES abrigos(id_abrigo),
    data_entrada TIMESTAMP NOT NULL,
    data_saida TIMESTAMP
);


-- PROCEDURES: usuarios
CREATE OR REPLACE PROCEDURE inserir_usuario (
  p_nome IN VARCHAR2, p_email IN VARCHAR2, p_senha IN VARCHAR2, p_tipo_usuario IN VARCHAR2
) AS BEGIN
  INSERT INTO usuarios (nome, email, senha, tipo_usuario) VALUES (p_nome, p_email, p_senha, p_tipo_usuario);
END;
/
CREATE OR REPLACE PROCEDURE atualizar_usuario (
  p_id_usuario IN NUMBER, p_nome IN VARCHAR2, p_email IN VARCHAR2, p_senha IN VARCHAR2, p_tipo_usuario IN VARCHAR2
) AS BEGIN
  UPDATE usuarios SET nome = p_nome, email = p_email, senha = p_senha, tipo_usuario = p_tipo_usuario WHERE id_usuario = p_id_usuario;
END;
/
CREATE OR REPLACE PROCEDURE deletar_usuario (p_id_usuario IN NUMBER) AS BEGIN
  DELETE FROM usuarios WHERE id_usuario = p_id_usuario;
END;
/

-- PROCEDURES: tipos_ocorrencia
CREATE OR REPLACE PROCEDURE inserir_tipo_ocorrencia (p_nome IN VARCHAR2) AS BEGIN
  INSERT INTO tipos_ocorrencia (nome) VALUES (p_nome);
END;
/
CREATE OR REPLACE PROCEDURE atualizar_tipo_ocorrencia (p_id_tipo IN NUMBER, p_nome IN VARCHAR2) AS BEGIN
  UPDATE tipos_ocorrencia SET nome = p_nome WHERE id_tipo = p_id_tipo;
END;
/
CREATE OR REPLACE PROCEDURE deletar_tipo_ocorrencia (p_id_tipo IN NUMBER) AS BEGIN
  DELETE FROM tipos_ocorrencia WHERE id_tipo = p_id_tipo;
END;
/

-- PROCEDURES: ocorrencias
CREATE OR REPLACE PROCEDURE inserir_ocorrencia (
  p_id_usuario IN NUMBER, p_id_tipo IN NUMBER, p_descricao IN VARCHAR2,
  p_latitude IN NUMBER, p_longitude IN NUMBER, p_data_ocorrencia IN TIMESTAMP,
  p_nivel_risco IN VARCHAR2, p_status IN VARCHAR2
) AS BEGIN
  INSERT INTO ocorrencias (id_usuario, id_tipo, descricao, latitude, longitude, data_ocorrencia, nivel_risco, status)
  VALUES (p_id_usuario, p_id_tipo, p_descricao, p_latitude, p_longitude, p_data_ocorrencia, p_nivel_risco, p_status);
END;
/
CREATE OR REPLACE PROCEDURE atualizar_ocorrencia (p_id_ocorrencia IN NUMBER, p_descricao IN VARCHAR2, p_status IN VARCHAR2) AS BEGIN
  UPDATE ocorrencias SET descricao = p_descricao, status = p_status WHERE id_ocorrencia = p_id_ocorrencia;
END;
/
CREATE OR REPLACE PROCEDURE deletar_ocorrencia (p_id_ocorrencia IN NUMBER) AS BEGIN
  DELETE FROM ocorrencias WHERE id_ocorrencia = p_id_ocorrencia;
END;
/

-- PROCEDURES: alertas
CREATE OR REPLACE PROCEDURE inserir_alerta (
  p_titulo IN VARCHAR2, p_mensagem IN VARCHAR2, p_nivel_urgencia IN VARCHAR2,
  p_id_ocorrencia IN NUMBER, p_fonte IN VARCHAR2
) AS BEGIN
  INSERT INTO alertas (titulo, mensagem, nivel_urgencia, id_ocorrencia, fonte)
  VALUES (p_titulo, p_mensagem, p_nivel_urgencia, p_id_ocorrencia, p_fonte);
END;
/
CREATE OR REPLACE PROCEDURE atualizar_alerta (p_id_alerta IN NUMBER, p_mensagem IN VARCHAR2) AS BEGIN
  UPDATE alertas SET mensagem = p_mensagem WHERE id_alerta = p_id_alerta;
END;
/
CREATE OR REPLACE PROCEDURE deletar_alerta (p_id_alerta IN NUMBER) AS BEGIN
  DELETE FROM alertas WHERE id_alerta = p_id_alerta;
END;
/

-- PROCEDURES: abrigos
CREATE OR REPLACE PROCEDURE inserir_abrigo (
  p_nome IN VARCHAR2, p_endereco IN VARCHAR2, p_capacidade_total IN NUMBER,
  p_vagas_disponiveis IN NUMBER, p_telefone IN VARCHAR2, p_status IN VARCHAR2
) AS BEGIN
  INSERT INTO abrigos (nome, endereco, capacidade_total, vagas_disponiveis, telefone, status)
  VALUES (p_nome, p_endereco, p_capacidade_total, p_vagas_disponiveis, p_telefone, p_status);
END;
/
CREATE OR REPLACE PROCEDURE atualizar_abrigo (p_id_abrigo IN NUMBER, p_vagas_disponiveis IN NUMBER, p_status IN VARCHAR2) AS BEGIN
  UPDATE abrigos SET vagas_disponiveis = p_vagas_disponiveis, status = p_status WHERE id_abrigo = p_id_abrigo;
END;
/
CREATE OR REPLACE PROCEDURE deletar_abrigo (p_id_abrigo IN NUMBER) AS BEGIN
  DELETE FROM abrigos WHERE id_abrigo = p_id_abrigo;
END;
/

-- PROCEDURES: checkins_abrigos
CREATE OR REPLACE PROCEDURE inserir_checkin (p_id_usuario IN NUMBER, p_id_abrigo IN NUMBER, p_data_entrada IN TIMESTAMP) AS BEGIN
  INSERT INTO checkins_abrigos (id_usuario, id_abrigo, data_entrada) VALUES (p_id_usuario, p_id_abrigo, p_data_entrada);
END;
/
CREATE OR REPLACE PROCEDURE atualizar_checkout (p_id_checkin IN NUMBER, p_data_saida IN TIMESTAMP) AS BEGIN
  UPDATE checkins_abrigos SET data_saida = p_data_saida WHERE id_checkin = p_id_checkin;
END;
/
CREATE OR REPLACE PROCEDURE deletar_checkin (p_id_checkin IN NUMBER) AS BEGIN
  DELETE FROM checkins_abrigos WHERE id_checkin = p_id_checkin;
END;
/


-- INSERÇÕES USANDO PROCEDURES PARA A TABELA: usuarios
BEGIN
  inserir_usuario('Ana Lima', 'ana@email.com', 'senha123', 'cidadao');
  inserir_usuario('Carlos Souza', 'carlos@email.com', 'senha123', 'voluntario');
  inserir_usuario('João Pedro', 'joao@email.com', 'senha123', 'orgao_publico');
  inserir_usuario('Maria Clara', 'maria@email.com', 'senha123', 'cidadao');
  inserir_usuario('Lucas Rocha', 'lucas@email.com', 'senha123', 'voluntario');
END;
/

-- INSERÇÕES USANDO PROCEDURES PARA A TABELA: tipos_ocorrencia
BEGIN
  inserir_tipo_ocorrencia('Enchente');
  inserir_tipo_ocorrencia('Deslizamento');
  inserir_tipo_ocorrencia('Incêndio');
  inserir_tipo_ocorrencia('Tempestade');
  inserir_tipo_ocorrencia('Terremoto');
END;
/

-- INSERÇÕES USANDO PROCEDURES PARA A TABELA: ocorrencias
BEGIN
  inserir_ocorrencia(1, 1, 'Rua alagada', -23.5612, -46.6558, SYSTIMESTAMP, 'alto', 'ativo');
  inserir_ocorrencia(2, 2, 'Deslizamento parcial', -23.5600, -46.6560, SYSTIMESTAMP, 'moderado', 'ativo');
  inserir_ocorrencia(3, 3, 'Fogo em vegetação', -23.5590, -46.6540, SYSTIMESTAMP, 'alto', 'resolvido');
  inserir_ocorrencia(4, 4, 'Ventos fortes derrubaram árvores', -23.5580, -46.6530, SYSTIMESTAMP, 'baixo', 'ativo');
  inserir_ocorrencia(5, 5, 'Tremor leve sentido no bairro', -23.5570, -46.6520, SYSTIMESTAMP, 'moderado', 'em análise');
END;
/

-- INSERÇÕES USANDO PROCEDURES PARA A TABELA: alertas
BEGIN
  inserir_alerta('Alerta de Enchente', 'Evite transitar pela região afetada', 'alta', 1, 'sistema');
  inserir_alerta('Deslizamento de terra', 'Risco de novos deslizamentos', 'media', 2, 'manual');
  inserir_alerta('Foco de incêndio', 'Área isolada pelos bombeiros', 'alta', 3, 'iot');
  inserir_alerta('Tempestade severa', 'Permaneça em locais cobertos', 'baixa', 4, 'sistema');
  inserir_alerta('Tremor registrado', 'Sem danos até o momento', 'media', 5, 'manual');
END;
/

-- INSERÇÕES USANDO PROCEDURES PARA A TABELA: abrigos
BEGIN
  inserir_abrigo('Abrigo Central', 'Rua das Flores, 100', 100, 75, '11999990000', 'ativo');
  inserir_abrigo('Abrigo Zona Sul', 'Av. Sul, 200', 150, 120, '11888887777', 'ativo');
  inserir_abrigo('Abrigo Norte', 'Rua da Paz, 300', 80, 65, '11777776666', 'ativo');
  inserir_abrigo('Abrigo Leste', 'Travessa Esperança, 50', 90, 45, '11666665555', 'lotado');
  inserir_abrigo('Abrigo Oeste', 'Rua das Árvores, 25', 60, 10, '11555554444', 'ativo');
END;
/

-- INSERÇÕES USANDO PROCEDURES PARA A TABELA: checkins_abrigos
BEGIN
  inserir_checkin(1, 1, SYSTIMESTAMP);
  inserir_checkin(2, 2, SYSTIMESTAMP);
  inserir_checkin(3, 3, SYSTIMESTAMP);
  inserir_checkin(4, 4, SYSTIMESTAMP);
  inserir_checkin(5, 5, SYSTIMESTAMP);
END;
/

